# Generated by Django 6.1.1 on 2026-10-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('year', models.IntegerField(max_length=2)),
                ('active_status', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
