# Generated by Django 6.1.1 on 2026-10-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_courses_students_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecturer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
        migrations.AddField(
            model_name='courses',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.lecturer'),
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='students.courses'),
        ),
    ]
